const TransactionTypes = {
    "pix": {"4028" : "ORDEM_PAGAMENTO_PIX", "4029" : "ORDEM_DEVOLUCAO_PIX", "4030" : "ORDEM_PAGAMENTO_QRDINAMICO_PIX", "4031" : "ESTORNO_ORDEM_RECEBIMENTO_PIX",
            "1007" : "CADASTRO_CHAVE_PIX", "1008" : "EXCLUSAO_CHAVE_PIX", "1009" : "REIVINDICA_CHAVE_PIX", "1010" : "CADASTRO_QRCODE_PIX", "1015" : "AGENDAMENTO_PIX",
            "1016" : "CANCELAMENTO_AGENDAMENTO_PIX", "1017" : "ALTERACAO_AGENDAMENTO_PIX", "1018" : "BUSCAR_AGENDAMENTO_PIX", "1025" : "NOTIFICAR_PIX",
            "2006" : "EXTRATO_PIX", "2007" : "VALIDAR_QRCODE_PIX", "2008" : "CONSULTA_CHAVE_PIX", "3028" : "ESTORNO_ORDEM_PAGAMENTO_PIX",
            "3029" : "ESTORNO_ORDEM_DEVOLUCAO_PIX", "3030" : "ESTORNO_ORDEM_PAGAMENTO_QRDINAMICO_PIX", "3031" : "ORDEM_RECEBIMENTO_PIX",
            "3038" : "ORDEM_RECEBIMENTO_DEVOLUCAO_PIX", "4038" : "ESTORNO_ORDEM_RECEBIMENTO_DEVOLUCAO_PIX", "4079": "ORDEM_PAGAMENTO_SAQUE_PIX"
           },

    "other": {"1000":"EMISSOR", "1001" : "PARCEIRO", "1002" : "CLIENTECONTA","1004" : "CLIENTECONTA_BANCO", "1005" : "CLIENTECONTA_PROCESSADORA", "0" : "OTHERS",
              "1006" : "ASSINATURA_TERMO", "1019" : "CONFIRMAR_EMAIL","1013" : "ENVIO_SMS_ALTERACAO_STATUS", "1014" : "ANEXO_OCORRENCIA", "1021" : "CANCELAMENTO_PEDIDO_BANCO",
              "1022" : "CANCELAMENTO_PEDIDO_CLIENTE", "1023" : "CANCELAMENTO_PEDIDO_PARCEIRO", "1024" : "PIN_CONTA", "1027" : "ALTERAR_EMAIL", "1028" : "ALTERAR_EMAIL_CONTA",
              "1030" : "RESET_SENHA_USUARIO", "1032" : "ANEXO_LOGO_PARCEIRO", "1033" : "LISTA_RESTRITIVA", "1097" : "FINANCIAMENTO_TROCA_APARELHO", "1098" : "FINANCIAMENTO_PROPOSTA",
              "1099" : "FINANCIAMENTO_CONTRATO", "1100" : "CLIENTE_TRAVEL", "1101" : "CONTRATO_TRAVEL", "1102" : "LOTE_TRAVEL", "1103" : "TRANSACOES_TRAVEL",
              "1104" : "GERACAO_SENHA_CLIENTE_TRAVEL", "1105" : "VALIDACAO_SENHA_CLIENTE_TRAVEL", "2001" : "SALDO", "2002" : "EXTRATO", "2004" : "SENHA",
              "2005" : "COMPROVANTE", "2015" :"DETALHE_EXTRATO", "2016" : "INFORME_DEPOSITO_DIGITAL", "2020" : "CONSULTA_PROPOSTA_PENDENTE_ANTECIPACAO",
              "2021" : "CONSULTA_CONVENIOS_ANTECIPACAO", "2022" : "CONSULTA_CONTRATOS_ANTECIPACAO", "2023" : "CONSULTA_MARGEM_ANTECIPACAO", "2024" : "CONSULTA_MARGEM_RENEGOCIACAO",
              "2025" : "PRIMEIRO_ACESSO_ONIDATA", "2026" : "CONSULTA_EXTRATO_CONTRATO_CLIENTE", "2027" : "CONSULTA_EXTRATO_CONTRATO_DETALHADO_CLIENTE", "2028" : "OBTER_RECEBIVEIS_CONTRATO_ONIDATA",
              "2029" : "CONSULTA_RELATORIO_CONTRATOS_ONIDATA", "2030" : "OBTER_DADOS_FUNCIONARIO_ONIDATA", "2031" : "ALTERAR_DADOS_FUNCIONARIO_ONIDATA","3055" : "CAMPANHA_ABERTURA_CONTA",
              "3056" : "CAMPANHA_INDIQUE_E_GANHE", "3057" : "CAMPANHA_CASHBACK", "3058": "CAMPANHA_CASHBACK_SMARTPHONE","3071" : "DEPOSITO_DIGITAL","3073" : "ESTORNO_DEBITO_CRIACAO_PEDIDO_TRAVEL",
              "3075" : "ESTORNO_DEBITO_RESTITUICAO_PEDIDO_TRAVEL","4039" : "ESTORNO_VALE_REFEICAO", "4040" : "ESTORNO_VALE_ALIMENTACAO", "4041" : "ESTORNO_VALE_COMBUSTIVEL",
              "4042" : "ESTORNO_VALE_TRANSPORTE", "4043" : "ESTORNO_VALE_CULTURA", "4044" : "ESTORNO_VALE_PEDAGIO", "4045" : "ESTORNO_AUXILIO_HOME_OFFICE", "4046" : "ESTORNO_PACOTE_DE_BENEFICIOS",
              "4047" : "ESTORNO_AUXILIO_ACADEMIA", "4048" : "ESTORNO_AUXILIO_FARMACIA", "4049": "ESTORNO_AUXILIO_EDUCACAO", "4050" : "ESTORNO_AUXILIO_CRECHE", "4051" : "ESTORNO_PLANO_DE_SAUDE",
              "4052" : "ESTORNO_RESCISAO_CONTRATUAL", "4053" : "EST_ADIANT_DESP_CORPORATIVAS", "4054" : "EST_REEMB_DESP_CORPORATIVAS", "4055" : "ESTORNO_CAMPANHA_ABERTURA_CONTA", 
              "4056" : "ESTORNO_CAMPANHA_INDIQUE_E_GANHE", "4057" : "ESTORNO_CAMPANHA_CASHBACK", "4059" : "ESTORNO_RECEBIVEIS", "4060" : "DEBITO_BLOQUEIO_JUDICIAL", "4061" : "TRANSFERENCIA_CONTA_JUDICIAL",
              "4062" : "ESTORNO_PREMIACAO", "4071" : "ESTORNO_DEPOSITO_DIGITAL", "4073" : "DEBITO_CRIACAO_PEDIDO_TRAVEL", "4074" : "ESTORNO_CREDITO_CRIACAO_PEDIDO_TRAVEL",
              "4075" : "DEBITO_RESTITUICAO_PEDIDO_TRAVEL", "4076" : "ESTORNO_CREDITO_RESTITUICAO_PEDIDO_TRAVEL", "4998" : "ESTORNO_RECEBIMENTO_DOC",
              "4999" : "SAQUE_ELO", "5000" : "BLOQ_FRAUDE", "5001" :"BLOQ_EXCEDEU_N_TENTATIVAS_DE_ACESSO", "5002" : "BLOQ_ROUBO", "5003" : "BLOQ_PERDA", "5004" : "BLOQ_SOLICITACAO_JUDICIAL",
              "5005" : "BLOQ_EMISSAO", "5006" : "BLOQ_EXTRAVIO", "5007" : "BLOQ_SUSPEITA_FRAUDE", "5008" : "BLOQ_SUSPEITA_PLD", "5009" : "BLOQ_CANCELADO_CLIENTE", "5010" : "BLOQ_PEDIDO_CLIENTE",
              "5011" : "BLOQ_DANIFICADO", "6000" : "DESBLOQ_CONTESTACAO_FRAUDE", "6001" : "DESBLOQ_POS_TENTATIVAS_ERRADAS", "6002" : "DESBLOQ_ROUBO", "6003" : "DESBLOQ_PERDA", "6004" : "DESBLOQ_SOLICITACAO_JUDICIAL",
              "6005" : "DESBLOQ_EMISSAO", "6006" : "DESBLOQ_PEDIDO_CLIENTE", "8000" : "CONSULTA_SALDO_ADQUIRENCIA", "8001" : "SOLICITACAO_PORTABILIDADE", "8002" : "CONSULTAR_PORTABILIDADE",
              "11001" : "ATUALIZAR_HEADER_FOOTER_NOTIFICACAO_SERVICE", "11002" : "ADICIONAR_BODY_NOTIFICACAO_SERVICE", "11003" : "ACIONAR_NOTIFICACAO_SERVICE", "12001" : "OBTER_CLIENTE_FINANCIAMENTO_MOBILE",
              "12002" : "CONSULTAR_CONTRATO_CLIENTE_FINANCIAMENTO_MOBILE", "13001" : "CONSULTAR_CONVENIOS_PUBLICOS", "13002" : "OBTER_CONVENIOS_PUBLICOS", "13003" : "ATUALIZAR_CONVENIO_PUBLICO", "13004" : "INSERIR_CONVENIOS_PUBLICOS"
            },

    "card": { "4022" : "COMPRA_CARTAO","1003" : "CARTAO", "1011" : "EMISSAO_CARTAO_FISICO", "1012" : "EMISSAO_CARTAO_VIRTUAL","1020" : "EMISSAO_2_VIA_CARTAO_FISICO" , "1026" : "APROVISIONAMENTO_CARTAO", "1029" : "PIN_CARTOES", 
              "1031" : "EMISSAO_CARTAO_FISICO_EM_LOTE", "1034" : "EMISSAO_2_VIA_CARTAO_FISICO_ISENTO_TAXA","2003" : "STATUS_CARTAO", "2017" : "CONSULTA_QRCODE_PAGAMENTO_ELO", "3022" : "ESTORNO_COMPRA_CARTAO", "9000" : "BLOQUEIO_CARTAO_ELO",
              "9001" :" DESBLOQUEIO_CARTAO_ELO", "9002" : "APROVAR_PAGAMENTO_QRCODE_ELO"
            },

    "boleto": {"4023" : "PAGAMENTO_BOLETO", "2009" : "VALIDACAO_PAGAMENTO_DE_CONTAS", "4032" : "SOLICITA_NOVO_BOLETO", "2010" : "VALIDACAO_PAGAMENTO_BOLETO","3023" : "ESTORNO_PAGAMENTO_BOLETO", "3035" : "CANCELAMENTO_BOLETO", "4009" : "PAGAMENTO_DE_CONTAS", "18000" : "PAGAMENTO_RECARGA_BENEFICIO", "18001" : "PAGAMENTO_VALE_REFEICAO",
               "18002" : "PAGAMENTO_VALE_ALIMENTACAO", "18003" : "PAGAMENTO_VALE_COMBUSTIVEL", "18004" : "PAGAMENTO_VALE_TRANSPORTE", "18006" : "PAGAMENTO_VALE_CULTURA", "18007" : "PAGAMENTO_VALE_PEDAGIO", "18008" : "PAGAMENTO_AUXILIO_HOME_OFFICE", "18009" : "PAGAMENTO_AUXILIO_ACADEMIA", "18010" : "PAGAMENTO_AUXILIO_FARMACIA",
               "18011" : "PAGAMENTO_AUXILIO_EDUCACAO", "18012" : "PAGAMENTO_AUXILIO_CRECHE", "18013" : "PAGAMENTO_AUXILIO_PLANO_DE_SAUDE", "18014" : "PAGAMENTO_RESCISAO_CONTRATUAL", "18015" : "PAGAMENTO_ADIANTAMENTO_DESPESAS_CORPORATIVAS", "18016" : "PAGAMENTO_REEMBOLSO_DESPESAS_CORPORATIVAS", "18017" : "PAGAMENTO_PREMIACAO",
               "19000" : "ESTORNO_PAGAMENTO_RECARGA_BENEFICIO", "19001" : "ESTORNO_PAGAMENTO_VALE_REFEICAO", "19002" : "ESTORNO_PAGAMENTO_VALE_ALIMENTACAO", "19003" : "ESTORNO_PAGAMENTO_VALE_COMBUSTIVEL", "19004" : "ESTORNO_PAGAMENTO_VALE_TRANSPORTE", "19006" : "ESTORNO_PAGAMENTO_VALE_CULTURA", "19007" : "ESTORNO_PAGAMENTO_VALE_PEDAGIO",
               "19008" : "ESTORNO_PAGAMENTO_AUXILIO_HOME_OFFICE", "19009" : "ESTORNO_PAGAMENTO_AUXILIO_ACADEMIA", "19010" : "ESTORNO_PAGAMENTO_AUXILIO_FARMACIA", "19011" : "ESTORNO_PAGAMENTO_AUXILIO_EDUCACAO", "19012" : "ESTORNO_PAGAMENTO_AUXILIO_CRECHE", "19013" : "ESTORNO_PAGAMENTO_AUXILIO_PLANO_DE_SAUDE",
               "19014" : "ESTORNO_PAGAMENTO_RESCISAO_CONTRATUAL", "19015" : "ESTORNO_PAGAMENTO_ADIANTAMENTO_DESPESAS_CORPORATIVAS", "19016" : "ESTORNO_PAGAMENTO_REEMBOLSO_DESPESAS_CORPORATIVAS", "19017" : "ESTORNO_PAGAMENTO_PREMIACAO","3001" : "RECARGA_VIA_BOLETO",
               },

    "ted": {"4019" : "ENVIO_TRANSFERENCIA_ENTRE_CARTOES","2011" : "AGENDAMENTO_TED", "3015" : "RECEBIMENTO_DE_TED", "3019" : "RECEBIMENTO_TRANSFERENCIA_ENTRE_CARTOES", "3997" : "RECEBIMENTO_TED_MSM_TITULARIDADE", "4012" : "ESTORNO_RECEBIMENTO_DE_TED", "4013" : "ESTORNO_RECEBIMENTO_TRANSF_ENTRE_CARTOES", "4015" : "ENVIO_DE_TED",
            "4997" : "ESTORNO_RECEB_TED_MSM_TITULARIDADE", "3012" : "ESTORNO_ENVIO_DE_TED", "3998" : "RECEBIMENTO_DOC"},

    "recharge": {"2012" : "CONSULTA_OPERADORAS_RECARGA_CELULAR", "2013" : "CONSULTA_OPERADORAS_RECARGA_SERVICOS", "2014" : "CONSULTA_VALORES_OPERADORA","3000" : "RECARGA_PELO_PARCEIRO", "3024" : "CARGA_ANTECIPACAO", "3026" : "CARGA_ANTECIPACAO_PARCELADA","4000" : "ESTORNO_RECARGA_PELO_PARCEIRO",
                 "4001" : "ESTORNO_RECARGA_VIA_BOLETO", "4010" : "RECARGA_DE_CELULAR", "4011" : "RECARGA_SERVICOS", "4024" : "ESTORNO_CARGA_ANTECIPACAO", "4026" : "ESTORNO_CARGA_ANTECIPACAO_PARCELADA"
                },

    "atm" : {"4014" : "SAQUE","2018" : "CONSULTA_SAQUE_ATM", "2019" : "CONSULTA_DEPOSITO_ATM", "3014" : "ESTORNO_SAQUE", "3999" : "ESTORNO_SAQUE_ELO", "4996" : "TARIFA_SAQUE_ELO"},

    "tarrifs": {"3002" : "ESTORNO_TARIFA_EMISSAO_CARTAO_FISICO", "3003" : "ESTORNO_TARIFA_RECARGA_VIA_BOLETO", "3004" : "ESTORNO_TARIFA_TED", "3005" : "ESTORNO_TARIFA_2_VIA", "3006" : "ESTORNO_TARIFA_CONTEST_CHARGEBACK", "3007" : "ESTORNO_TARIFA_TRANSF_ENTRE_CARTOES", "3008": "ESTORNO_TARIFA_SAQUE", "3009" : "ESTORNO_PAGTO_DE_CONTAS",
                "3010" : "ESTORNO_RECARGA_CELULAR", "3011" : "ESTORNO_RECARGA_SERVICOS", "3013" : "ESTORNO_ENVIO_TRANSF_ENTRE_CARTOES", "3016" : "ESTORNO_TARIFA_PAGTO_DE_CONTAS", "3017" : "ESTORNO_TARIFA_RECARGA_DE_CELULAR", "3018" : "ESTORNO_TARIFA_RECARGA_DE_SERVICOS", "3020": "ESTORNO_TARIFA_ENVIO_CARTAO_FISICO",
                "3021" : "ESTORNO_TARIFA_ENVIO_TRANSFERENCIA_ENTRE_CONTAS", "3025" : "ESTORNO_TARIFA_ANTECIPACAO",  "3027" : "ESTORNO_TARIFA_ANTECIPACAO_PARCELADA","3033" : "ESTORNO_TARIFA_NOVO_BOLETO","3072" : "ESTORNO_TARIFA_DEPOSITO_DIGITAL", "3996" : "ESTORNO_TARIFA_SAQUE_ELO",  "4007" : "TARIFA_TRANSF_ENTRE_CARTOES", "4008" : "TARIFA_SAQUE",
                "4016" : "TARIFA_PAGAMENTO_DE_CONTAS", "4017" : "TARIFA_RECARGA_DE_CELULAR", "4018" : "TARIFA_RECARGA_DE_SERVICOS",  "4020" : "TARIFA_ENVIO_CARTAO_FISICO", "4021" : "TARIFA_ENVIO_TRANSFERENCIA_ENTRE_CONTAS", "4025" : "TARIFA_ANTECIPACAO",
                "3036" : "ESTORNO_TARIFA_EMISSAO_CARTAO_VIRTUAL", "4027" : "TARIFA_CARGA_ANTECIPACAO_PARCELADA", "4033" : "TARIFA_NOVO_BOLETO", "4035" : "TARIFA_EMISSAO_CARTAO_VIRTUAL", "4037" : "ESTORNO_CREDITO_TRAVEL", "4004" : "TARIFA_DE_TED", "4002" : "TARIFA_EMISSAO_CARTAO_FISICO", "4003" : "TARIFA_RECARGA_VIA_BOLETO", "4005" : "TARIFA_2_VIA",
                "4006" : "TARIFA_CONTESTACAO_CHARGEBACK", "4072" : "TARIFA_DEPOSITO_DIGITAL"
               },

    "credit" : {"3037" : "CREDITO_TRAVEL", "3039" : "CREDITO_VALE_REFEICAO", "3040" : "CREDITO_VALE_ALIMENTACAO", "3041" : "CREDITO_VALE_COMBUSTIVEL", "3042" : "CREDITO_VALE_TRANSPORTE", "3043" : "CREDITO_VALE_CULTURA", "3044" : "CREDITO_VALE_PEDAGIO", "3045" : "CREDITO_AUXILIO_HOME_OFFICE", "3046" : "CREDITO_PACOTE_DE_BENEFICIOS",
                "3047" : "CREDITO_AUXILIO_ACADEMIA", "3048" : "CREDITO_AUXILIO_FARMACIA","3049" : "CREDITO_AUXILIO_EDUCACAO", "3050" : "CREDITO_AUXILIO_CRECHE", "3051" : "CREDITO_PLANO_DE_SAUDE", "3052" : "CREDITO_RESCISAO_CONTRATUAL", "3053" : "CRED_ADIANT_DESP_CORPORATIVAS", "3054" : "CRED_REEMB_DESP_CORPORATIVAS", "3059" : "CREDITO_RECEBIVEIS",
                "3060" : "CREDITO_BLOQUEIO_JUDICIAL", "3062" : "CREDITO_PREMIACAO", "3074" : "CREDITO_CRIACAO_PEDIDO_TRAVEL", "3076" : "CREDITO_RESTITUICAO_PEDIDO_TRAVEL"
               },
    "dimo QR code" : {"4078": "DIMO_PAY"}
}

const typeArray = Object.keys(TransactionTypes);

function isTransactionPresent() {

    this.findTransactionType = function(typeNumber) {
    for(var txn=0; txn < typeArray.length ; txn++) {
        let searchArray = Object.keys(TransactionTypes[typeArray[txn]]);
        for( var txnTypenum=0; txnTypenum < searchArray.length; txnTypenum++) {
            if (searchArray[txnTypenum] === typeNumber) {
                return typeArray[txn];
            }
         }
    }
  }

  this.availableTransactionTypes = function() {
      let availableTypes = ["pix","card","boleto", "ted", "recharge", "atm", "Compra a Vista ELO", "Schedule", "dimo QR code"];
      return availableTypes;
  }

  this.findTxnType = function(typeId){
    let allTypesArr = ["pix","card","boleto", "ted", "recharge", "atm", "tarrifs", "credit", "dimo QR code","other"];
    for(let index = 0; index < allTypesArr.length;index++){
        let typeObj = allTypesArr[index];
        let serachJson = TransactionTypes[typeObj];
        if(serachJson[typeId] !== undefined || serachJson[typeId] != null){
            return typeObj;
        }
    }
    return "other";
  }

}

export default new isTransactionPresent();