// Unblock Status Terms
export const ACCOUNT_STATUS_NOT_FOUND = 404;
export const ACCOUNT_STATUS_ACTIVE = 'ATIVA';
export const ACCOUNT_STATUS_INACTIVE = 'INATIVA';
export const ACCOUNT_STATUS_CLOSED = 'ENCERRADA';
export const ACCOUNT_STATUS_BLOCKED = 'BLOQUEADA';
export const ACCOUNT_STATUS_PROGRESS = 'DESBLOQUEIO_ANDAMENTO';

// Unblock Account Screen Terms
export const UNBLOCK_ACCOUNT_SECURITY = 'UNBLOCK_ACCOUNT_SECURITY';
export const UNBLOCK_ACCOUNT_SELFIE_INFO = 'UNBLOCK_ACCOUNT_SELFIE_INFO';
export const UNBLOCK_ACCOUNT_FACE_AUTH = 'UNBLOCK_ACCOUNT_FACE_AUTH';
export const UNBLOCK_ACCOUNT_SELFIE_REVIEW = 'UNBLOCK_ACCOUNT_SELFIE_REVIEW';
export const UNBLOCK_ACCOUNT_PROGRESS = 'UNBLOCK_ACCOUNT_PROGRESS';
export const UNBLOCK_ACCOUNT_FAILED = 'UNBLOCK_ACCOUNT_FAILED';
export const UNBLOCK_ACCOUNT_SUCCESS = 'UNBLOCK_ACCOUNT_SUCCESS';

// Extra Terms
export const CAF_IMG_MAX_SIZE = 1024 * 1024 * 3;
export const CAF_LOGS = "CAF_FACELIVENESS";
export const CAF_VALIDATION = "CAF_VALIDATION";
export const FACE_LIVELINESS = "FACE_LIVELINESS";
export const FACELIVENESS_SUCCESS = "FACELIVENESS_SUCCESS";
export const FACELIVENESS_FAILURE = "FACELIVENESS_FAILURE";
export const FACELIVENESS_URI = "GET_LIVENESS_METRICS_FOR_CAF";
export const CAMERA_PERMISSION = "android.permission.CAMERA";