export const DEFAULT_TIMEZONE = 'America/Sao_Paulo';

// STATUS TYPES
export const STATUS_READY = 'READY';
export const STATUS_LAUNCH = 'LAUNCH';
export const STATUS_COMPLETE = 'COMPLETE';

// REWARDS TYPES
export const REWARD_TYPE_CASH = 'CASH';
export const REWARD_TYPE_COUPON = 'COUPON';
export const REWARD_TYPE_LUCKY_NUMBER = 'LUCKY_NUMBER';

// REWARD CLAIM / OCCURRENCE
export const REWARD_CLAIM_DIRECT = 'DIRECT';
export const REWARD_CLAIM_REDEEMED = 'REDEEMED';
export const REWARD_OCCURRENCE_ONE_TIME = 'ONE_TIME';

// TASKS TYPES
export const TASK_DIMO_PIX_CASHOUT = 'DIMO_PIX_CASHOUT';
export const TASK_DIMO_CARD_CASHOUT = 'DIMO_CARD_CASHOUT';
export const TASK_DIMO_BOLETO_CASHOUT = 'DIMO_BOLETO_CASHOUT';
export const TASK_DIMO_RECHARGE_CASHOUT = 'DIMO_RECHARGE_CASHOUT';
export const TASK_DIMO_DEBIT_CARD_CASHOUT = 'DIMO_DEBIT_CARD_CASHOUT';
export const TASK_DIMO_FGTS_LOAN_APPROVED = 'DIMO_FGTS_LOAN_APPROVED';
export const TASK_DIMO_CREDIT_CARD_CASHOUT = 'DIMO_CREDIT_CARD_CASHOUT';
export const TASK_DIMO_CREDIT_CARD_REINVEST = 'DIMO_CREDIT_CARD_REINVEST';
export const TASK_DIMO_CREDIT_CARD_ONBOARDING = 'DIMO_CREDIT_CARD_ONBOARDING';

// PRIZE TYPES
export const PRIZE_TYPE_PHONE = 'MOTO_PHONE';
export const PRIZE_TYPE_COUPON = 'COUPON';

// EXTRA KEYS
export const CONSTRAINT_KEY_TYPE = 'KEY_TYPE';

// ACTION TYPES
export const ACTION_AVAILABLE = 'AVAILABLE';
export const ACTION_COMPLETED = 'COMPLETE';
export const ACTION_LOCKED = 'LOCKED';

// COMPLETE TYPES
export const COMPLETE_TYPE_AND = 'AND';
export const COMPLETE_TYPE_OR = 'OR';
export const COMPLETE_TYPE_NA = 'NA';

// REWARD TAB INDEXES
export const PLAY_DIMO_TAB_INDEX = 0;
export const OFFERS_TAB_INDEX = 1;
export const ALL_REWARDS_TAB_INDEX = 2;

// REWARD TAB ACTIONS
export const OFFERS_TAB_ACTION = "allOffers";
export const PLAY_DIMO_TAB_ACTION = "allPrograms";
export const ALL_REWARDS_TAB_ACTION = "allRewards";

// QUANTIFIER TYPES
export const QUANTIFIER_TYPE_COUNT = 'EVERY_COUNT';
export const QUANTIFIER_TYPE_AMOUNT = 'EVERY_VALUE';

// SHARE TYPES
export const SHARE_TYPE_PHONE_PROGRAM = 'phone_program';
export const SHARE_TYPE_COUPON_PROGRAM = 'coupon_program';
export const SHARE_TYPE_PHONE_REWARD = 'phone_reward';
export const SHARE_TYPE_COUPON_REWARD = 'coupon_reward';

// COUPON VALUE TYPES
export const COUPON_TYPE_FLAT = 'FLAT';
export const COUPON_TYPE_LINK = 'LINK';
export const COUPON_TYPE_PERCENT = 'PERCENT';

// TASK TERMS
export const INFINITE_TERM_NUMBER = 1500;

// REWARD TYPES ARRAY
export const REWARD_TYPES = {
    COUPON: 'Coupon',
    LUCKY_NUMBER: 'Lucky Number',
};